### ISSUE TITLE
ParseError on value ":" in struct inheritance

### ISSUE THREAD

**Issue by acascone** [RemedyIT/ridl#42]
**Version**
2.7.1

**Describe the bug**
I'm seeing a `parse error on value ":" (":")` on line 5 of the `test.idl` listed below:

```
module A {
	struct B {
		long field1;
	};
	struct C : B {
		long field2;
	};
};
```

If I remove the inheritance on `B` from `C`, it parses the file as expected.

**To Reproduce**
`./bin/ridlc test.idl`

**Expected behavior**
I would expect this file to parse struct inheritance with running into an error. I understand that the test `writer.rb` may not support printing at the moment.

**Environment:**
- Ubuntu 20.04, also observed on 18.04
- ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
- 2.7.1

**Output**

```
$ ./bin/ridlc test.idl -v
RIDL - parsing test.idl
IDL::ParseError: 
parse error on value ":" (":")
    test.idl: line 5, column 11

```

**Additional context**
I'm not a ruby developer, so the issue may be of my own creation.

I can provide the output from `--debug` if that would help, but it's rather verbose.

**Comment by mcorino** [comment]
RIDL is IDL 3 compliant which does not support struct inheritance.

**Comment by jwillemsen** [comment]
As part of our commercial support services (see https://www.remedy.nl/services/overview.html) we could add support for struct inheritance, please contact sales@remedy.nl when you want to discuss that in more detail.
